CSULA-USU/web

package.json
src/modules/Footer/Footer.tsx
src/modules/UpcomingEvents/UpcomingEvents.tsx
yarn.lock

Ensures that the footer is aligned in the center and includes Instagram icon.

feat: centers footer

---

src/modules/BoardOfDirectors/BoardOfDirectorsCTA.tsx

Adds fluid container in inner board of containers cta container div

chore: add fluid container in board of directors cta

---

src/pages/contact/index.tsx

size attribute for input tag has errors
rows and cols attribute for text area tag has errors

feat: adds contact info

---

src/modules/Nav/NavItems.tsx

corrects routing for tenants page on dropdown nav

fix: corrects routing for nav item dropdown for tenants page

---

src/pages/ccc/index.tsx

Updates the GSRC blurb per programmer email

chore: updates GSRC blurb

---

src/modules/HomeHeader/HomeHeader.tsx

John changed his mind about the header. He wants to re-add a welcome text at the top.

chore: adds welcome text to header

---

src/pages/about/tenants.tsx

This PR uses the generic modal on the tenant cards.

update: add modals to tenant cards

---

src/data/distinguishedWomenAwardsHonorees.json
src/pages/ccc/distinguished-women-awards.tsx

This PR also adds the remaining honorees to json.

update: adds expandable to the honorees section 

---

src/pages/csi/student-orgs.tsx

per the advice of the CSI coordinator, cards have been added and edited and made more relevant. Copywrite changed. Make resource slightly more responsive. Update top buttons to make more sense and make more functional

chore: update links and relevant cards for csi

---

src/pages/governance/student-leader-elections.tsx

Need assistance adjusting image size.

chore: adds responsive header

---

src/data/staff.json

Populated remaining staff members using pre-existing staff card

chore:populate remaining staff members

---

src/pages/operations/index.tsx

This PR uses video and images operations took. The video is used as a background in the header and might need adjustment for responsiveness.

feat: added operations images a video. Used video as header

---

src/modules/Footer/Footer.tsx

Added needed capitalization to footer

chore:edit footer

---

src/pages/index.tsx

Fixed grammar issue in "U-Krew" banner in upcoming events on home page

chore:fix u-krew grammar on main page

---

src/data/staff.json
src/pages/staff/index.tsx

Fix typo in Staff Page header & change ampersands to "and"

chore: fix staff page typos

---

src/data/departments.json

Change ampersands on department page to "and"

chore:add dept page accessibility

---

package.json
src/data/departments.json
src/data/distinguishedWomenAwardsHonorees.json
src/data/employment.json
src/pages/ccc/distinguished-women-awards.tsx
src/pages/ccc/index.tsx
src/pages/employment/index.tsx
src/pages/operations/meeting-rooms/[id].tsx
yarn.lock

Inverted award year ordering: most recent awards listed first

chore:edit women awards

---

package.json
src/data/departments.json
src/data/employment.json
src/pages/ccc/cultural-grads.tsx
src/pages/ccc/index.tsx
src/pages/employment/index.tsx
src/pages/operations/meeting-rooms/[id].tsx
yarn.lock

Corrected APIDA grad times and number of tickets

chore:edit apida grad

---

package.json
src/data/departments.json
src/data/employment.json
src/pages/ccc/index.tsx
src/pages/csi/index.tsx
src/pages/employment/index.tsx
src/pages/operations/meeting-rooms/[id].tsx
yarn.lock

chore:edit csi home accessibility

---

package.json
src/data/departments.json
src/data/employment.json
src/pages/ccc/index.tsx
src/pages/csi/forms.tsx
src/pages/employment/index.tsx
src/pages/operations/meeting-rooms/[id].tsx
yarn.lock

Corrected typos on CSI Forms page

chore:edit csi forms

---

package.json
src/data/departments.json
src/data/employment.json
src/pages/ccc/index.tsx
src/pages/csi/geek.tsx
src/pages/employment/index.tsx
src/pages/operations/meeting-rooms/[id].tsx
yarn.lock

chore:edit geek faq

---

src/data/acuiAwards.json

Chore:fix graffix typo

---

src/partials/BODDownloads.tsx

Removed agenda and meetings download sections on public docs page

chore:remove agenda and meetings

---

src/data/navMap.json
src/pages/governance/index.tsx

Fixed typos on governance page and changed archive drop down nav

chore:fix misc typos

---

src/data/employment.json

Added full time job listing for PASRC

chore:add-pasrc-job

---

src/data/staff.json

chore: yeeted karin

---

src/data/staff.json

chore: update frangelo job title

---

src/data/staff.json

Revert "chore: update frangelo job title"

---

src/data/employment.json
src/data/staff.json

Frangelo title change & Account tech job listing removal

chore:frangelo and job listing

---

src/pages/index.tsx

Added thumbnail meta tag for the home page when linking website

chore:add thumbnail img for home page

---

src/pages/index.tsx

Revert "chore: homepage preview image"

---

src/data/howToVoteMobile.json
src/data/howToVoteWeb.json
src/pages/about/services.tsx
src/pages/ccc/apisrc/index.tsx
src/pages/ccc/distinguished-women-awards.tsx
src/pages/ccc/pasrc/index.tsx
src/pages/events/index.tsx
src/pages/governance/index.tsx
src/pages/governance/meet-the-board.tsx
src/pages/operations/index.tsx
src/pages/operations/meeting-rooms/index.tsx
src/pages/recreation/gene.tsx
src/partials/PublicInspectionDocuments.tsx

Chore:fix typos and punctuation

---

src/modules/Footer/Footer.tsx

Added summer building hours to the footer

chore:add business hours

---

src/pages/ccc/apisrc/index.tsx
src/pages/ccc/clsrc/index.tsx
src/pages/ccc/gsrc/index.tsx
src/pages/ccc/pasrc/index.tsx

This PR removes galleries from ccc department pages.

update: remove galleries in ccc department pages

---

src/data/search-directory.json

Filled out empty search description for the Departments page

chore:add dept search description

---

src/pages/about/services.tsx

Changed a.m./p.m. back to AM/PM

chore:revert am pm case

---

src/data/board-members.json

Moved remaining bod images off of github and onto dropbox

chore:move bod images to dropbox

---

src/components/StaffCard/StaffCard.tsx
src/data/board-members.json

Changed height of staff card name section to put BOD titles & names in line

chore:fix staff card sizing

---

src/data/search-directory.json

Added missing periods in search card descriptions

chore:search card punctuation

---

src/pages/about/index.tsx

chore:update map

---

src/data/staff.json

Update staff titles on staff page.

chore:update staff titles

---

src/pages/recreation/gene.tsx

Changed dropbox link following dropbox fix for update that broke safari pdf view

chore: program portfolio button pdf fix

---

src/data/employment.json

Added job postings for FSL coordinator and admin analyst

chore:update ft job postings

---

src/data/public-document-archives.json
src/partials/BODDownloads.tsx

Moved FY22-23 files to archives, added FY23-24 files

Chore:update bod archives 23fy

---

src/modules/Footer/Footer.tsx

Updated Saturday building hours

chore: update sat building hours

---

src/data/staff.json

chore: remove anh

---

src/data/employment.json

Added PASRC Coordinator job listing

chore:add pasrc coord job

---

src/data/employment.json

Rearranged FT job listings in alphabetical order

chore: alphabetize job listings

---

src/data/staff.json

chore:remove laura

---

src/pages/staff/index.tsx

Added group photo of full-time to staff page

chore:add group staff photo

---

src/data/meetingRooms.json
src/pages/operations/meeting-rooms/[id].tsx
src/pages/operations/meeting-rooms/index.tsx

Update room rental prices + grammatical cleanup

chore:update meeting room prices

---

package.json
yarn.lock

Revert "fix: update babel/core and styled-components"

---

src/components/Card/Card.tsx
src/components/DescriptionCard/DescriptionCard.tsx
src/data/recreation.json
src/pages/csi/index.tsx
src/pages/recreation/gene.tsx

Revert "Chore/gene updates"

---

src/modules/Nav/Nav.tsx

Reverts CSULA-USU/web#1057
modals no longer work properly and are covered by the nav

Revert "chore: make nav sticky "

---

src/components/StaffCard/StaffCardWithModal.tsx
src/modules/GenericModal/GenericModal.tsx
src/pages/graffix/index.tsx

Reverts CSULA-USU/web#1082
Changes undetected by github

Revert "fix: change staff card desktop styling & made responsive, Generic modal changes in Graffix page "

---

src/modules/CulturalGradsHeader/CulturalGradsHeader.tsx
src/pages/_document.tsx

this message is only visible to those who have disabled Javascript. It's important to have this so that they can know why the website isn't working on their device.

fix: add meaningful noscript message 

---

src/modules/CulturalGradsHeader/CulturalGradsHeader.tsx

Reverts CSULA-USU/web#1157. This ADDS alerts.. it seems that it alerts regardless as long as the noscript element exists on the page.

Revert "fix: return removed pause button from cultural grads carousel and make it accessible"

---

package.json
yarn.lock

Fix authorization bypass in Next.js middleware. 
Despite us not being affected, as we host the website on Vercel, still good to know to fix

fix: next authorization bypass fix
